apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    username: ENC[AES256_GCM,data:l9+AP5r2tF4=,iv:rcEliR4qMxA0Wlx206AtAdbbYj4bl16Yy4QZcRDsEQI=,tag:fzjJGCs6Vf9QQpd7/o7bqw==,type:str]
    password: ENC[AES256_GCM,data:GJbn6DBKl7q88V19ulUNRw==,iv:ad+InLDnfWP7uDa9b0H+mj6O7gM4dygbl+J12tvXDEY=,tag:67GzA7ssDRxh/is68GZZ2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-23T23:26:53Z'
    mac: ENC[AES256_GCM,data:uh5gyccW1LbZsVEdT99QDvY0CrtIDpftEWR0CeR9ZhFf5Hnp5U5G4wfiZxa/z38yUZpaindt+gZAv9EVVslqsSJJylU/wuKB4CS2JYcGxnn9p/sArJE9IMJSU3hRuh7boTtFaQgv0sPNH5ojiHvD1CXmRUH0wtvqlwpWijRXWiM=,iv:trSDSwpmuFB0KNmKVPOncZgZyCNiDczK4sOEtNr98sU=,tag:SNJEy1nhRkfsSGVcCRWYCA==,type:str]
    pgp:
    -   created_at: '2020-09-23T23:26:53Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA4ewWWewNLhTAQf/daE/s0uE6gyg4yuNIh5WS4E65gaVsTvusNJkmdYdhUiw
            IpfUrZNwBqq6uEjBoxwftkQdX/8gvvp5hD8kNSQ7ZzPjxJFgN9b6gFzv5YKj9NiA
            DHbl1e1QsleXhZ3UKYtPhjhZv69COpQfkst6bJhcG8P2V3YQO8/6m5K7YR6b2P3d
            eGmYU++m0fJskoI7xPzpiv3UDURPeGIs5FylQ56fA307nKLufCWJ8WLO8MFJ5FND
            tNEYul5hYeRsT6uhuowke7O19h+MmAqYwYZ3JGyIbJNcxCoj31ruIfMZX+opm/zT
            MQEFQdOixynmhKPg86g28DyMEPKIelg/iEllulCLEdJeAayFJ3m3qiUQ5hqBNoNU
            5auJFxsianJ/gKmasV+uoN9nwP3+3jZHfR/Xa9t8g4g8X+g8xkyjt0ZP5xuUhuEW
            RG+wdSbroiq1sCnj+43w3OwR4RmqGOwr8rXh7P+RGQ==
            =d73J
            -----END PGP MESSAGE-----
        fp: CD1AFE846A21A236CEF18FF56555786B3A496099
    encrypted_regex: ^(data|stringData)$
    version: 3.6.0
